### ISSUE TITLE
app crashes after "get all friend dialogue " and unfortunately ,RivChat has stopped please help me 

### ISSUE THREAD

**Issue by Bandar-Ameen** [hieuapp/android-firebase-chat#23]
--------- beginning of crash
10-26 18:20:12.547 4590-4590/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.hieuapp.rivchat, PID: 4590
                                                 java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.rivchat.model.User.name' on a null object reference
                                                     at com.android.rivchat.ui.UserProfileFragment.setupArrayListInfo(UserProfileFragment.java:243)
                                                     at com.android.rivchat.ui.UserProfileFragment$1.onDataChange(UserProfileFragment.java:93)
                                                     at com.google.firebase.database.Query$1.onDataChange(Unknown Source)
                                                     at com.google.android.gms.internal.zzaie.zza(Unknown Source)
                                                     at com.google.android.gms.internal.zzaje.zzcta(Unknown Source)
                                                     at com.google.android.gms.internal.zzajh$1.run(Unknown Source)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by hieuapp** [comment]
at UserProfileFragment.java:243
java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.android.rivchat.model.User.name' on a null object reference

You fix this bug by check null object User before call getName.

**Comment by afifandika** [comment]
i have same problem, can u help me? @hieuapp

**Comment by hieuapp** [comment]
Please check my issue number #28

**Comment by bontanksakti84** [comment]
just create check null at your code

if(myAccount!=null){
                setupArrayListInfo(myAccount);

                if(infoAdapter != null){
                    infoAdapter.notifyDataSetChanged();
                }

                if(tvUserName != null){
                    tvUserName.setText(myAccount.name);
                }

                setImageAvatar(context, myAccount.avata);
                SharedPreferenceHelper preferenceHelper = SharedPreferenceHelper.getInstance(context);
                preferenceHelper.saveUserInfo(myAccount);
            }
